name: Image

on:
    push:
        branches: [ master ]

jobs:
    push-image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: docker build -t "ghcr.io/stck/adminer:4" -f ./Dockerfile .
            - name: Login to Packages Container registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Push to registry
              run: docker push "ghcr.io/stck/adminer:4"
